package com.bjss.desk_booking.desk;


import com.bjss.desk_booking.booking.Booking;
import com.bjss.desk_booking.office.Office;
import org.springframework.data.annotation.Transient;
import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Entity /*Spring boot annotation for defining this class is mapped to database*/
public class Desk {

    @Id //defining deskId variable is the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) //deskId variable will be auto generated by Database
    private int deskId; //Id of the Desk
    private String deskName; //Name of the Desk
    private String deskType; //Type of the desk.i.e-Standing,workstation
    private String deskPosition; // Position of the desk. i.e-Window side, kitchen side,Annex
    private int monitorOption; //How many monitor does this desk have
    private String deskStatus; //Status of the desk. i.e-Fully functional, Broken lan port
    private String deskImageName; //Image name of the desk in the local storage


    @OneToMany(mappedBy = "desk")  //Creating one to many relation with booking class and Using user object from Booking class
    List<Booking> bookingList = new ArrayList<>();

    @ManyToOne  //creating Many to one relation with office
    @JoinColumn(name = "office_id", nullable = false)
    //officeId from user class will be the foreign key in the booking table
    private Office office;


            /*Constructor*/
    public Desk(String name, Office office, String deskType, String deskPosition, int monitorOption) {
        this.deskName = name;
        this.office = office;
        this.deskType = deskType;
        this.deskPosition = deskPosition;
        this.monitorOption = monitorOption;
    }

    public Desk() {
    }
            /*Constructor Ends */


    //Get the path of the image from local storage
    @Transient //This Variable will not be mapped into database
    public String getPhotosImagePath() {
        if (deskName == null || deskId == -1) return null; //if the deskName is null or the deskId is null it will return -1

        return "desk/" + deskId + "/" + deskImageName;
    }



    /*All the getter setter method starts here*/

    public String getDeskImageName() {
        return deskImageName;
    }
    public void setDeskImageName(String deskImageName) {
        this.deskImageName = deskImageName;
    }

    public Office getOffice() {
        return office;
    }

    public void setOffice(Office office) {
        this.office = office;
    }

    public String getDeskStatus() {
        return deskStatus;
    }

    public void setDeskStatus(String deskStatus) {
        this.deskStatus = deskStatus;
    }

    public int getDeskID() {
        return deskId;
    }

    public void setDeskID(int deskID) {
        this.deskId = deskID;
    }

    public void setName(String name) {
        this.deskName = name;
    }

    public String getDeskName() {
        return deskName;
    }

    public void setDeskName(String deskName) {
        this.deskName = deskName;
    }

    public String getDeskType() {
        return deskType;
    }

    public void setDeskType(String deskType) {
        this.deskType = deskType;
    }

    public String getDeskPosition() {
        return deskPosition;
    }

    public void setDeskPosition(String deskPosition) {
        this.deskPosition = deskPosition;
    }

    public int getMonitorOption() {
        return monitorOption;
    }

    public void setMonitorOption(int monitorOption) {
        this.monitorOption = monitorOption;
    }

    public String getName() {
        return deskName;
    }

    /*All the getter setter method ends here*/

}
